#!/usr/bin/env python3
"""Sync the pinned tag-showcase test fixture from the live sample workspace.

`src-tauri/tests/sample-workspaces/tag-showcase` is the user-editable demo
opened via the app's **Open workspace** action. `src-tauri/tests/fixtures/tag-showcase`
is a pinned snapshot of it used by
`workspace::loader::tests::rust_loads_the_tag_showcase_workspace` — kept as a
separate copy on purpose, so editing the live demo while exploring the app
can never break that test. The two live near each other for easy comparison,
but only the fixture copy is actual test data; the live one is mutable demo
content and must never be pruned or regenerated by test tooling. See the
fixture's own README.md for the full rationale. The two must still agree in
content, so run this after editing the live demo's charts, transits, or
workspace.yaml:

    python3 scripts/sync-tag-showcase-fixture.py          # copy + report
    python3 scripts/sync-tag-showcase-fixture.py --check  # exit 1 if they'd differ

Only each side's own README.md is left alone — the live one is a user-facing
walkthrough, the fixture's documents why it's pinned, and they are meant to
read differently.

No dependencies - stdlib Python 3 only.
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "src-tauri" / "tests" / "sample-workspaces" / "tag-showcase"
FIXTURE = REPO_ROOT / "src-tauri" / "tests" / "fixtures" / "tag-showcase"
IGNORED_NAMES = {"README.md"}


def iter_synced_relative_paths(root: Path) -> list[str]:
    return sorted(
        str(path.relative_to(root))
        for path in root.rglob("*")
        if path.is_file() and path.name not in IGNORED_NAMES
    )


def find_differences() -> tuple[list[str], list[str], list[str]]:
    """Returns (only_in_source, only_in_fixture, content_differs)."""
    source_paths = set(iter_synced_relative_paths(SOURCE))
    fixture_paths = set(iter_synced_relative_paths(FIXTURE))
    only_in_source = sorted(source_paths - fixture_paths)
    only_in_fixture = sorted(fixture_paths - source_paths)
    content_differs = sorted(
        rel
        for rel in source_paths & fixture_paths
        if not filecmp.cmp(SOURCE / rel, FIXTURE / rel, shallow=False)
    )
    return only_in_source, only_in_fixture, content_differs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift and exit 1 without writing anything",
    )
    args = parser.parse_args()

    only_in_source, only_in_fixture, content_differs = find_differences()
    if not (only_in_source or only_in_fixture or content_differs):
        print("tag-showcase fixture already matches the live sample.")
        return 0

    for rel in only_in_source:
        print(f"only in live sample (would add to fixture): {rel}")
    for rel in only_in_fixture:
        print(f"only in fixture (would remove, not in live sample): {rel}")
    for rel in content_differs:
        print(f"content differs (would copy from live sample): {rel}")

    if args.check:
        return 1

    for rel in only_in_fixture:
        (FIXTURE / rel).unlink()
    for rel in only_in_source + content_differs:
        destination = FIXTURE / rel
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(SOURCE / rel, destination)

    print(f"synced {len(only_in_source) + len(content_differs)} file(s) into {FIXTURE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
